version: '3.8'

services:
  gtfs-rt-feed:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEV_MODE=true 